# Generated by Django 3.2.4 on 2021-11-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='storie_img')),
            ],
        ),
    ]
