# Generated by Django 3.2.4 on 2021-11-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_storie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storie',
            name='Owner',
            field=models.CharField(max_length=100),
        ),
    ]
