# Generated by Django 3.2.4 on 2021-11-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_storie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storie',
            name='Body',
            field=models.CharField(max_length=700),
        ),
    ]
