# Generated by Django 3.2.4 on 2021-11-02 22:35

import Register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, validators=[Register.models.validate_field])),
                ('Lastname', models.CharField(max_length=50)),
                ('Picture', models.ImageField(upload_to='pictures')),
                ('Password', models.CharField(default='', max_length=400, validators=[Register.models.validate_pass])),
                ('Salt', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
