# Generated by Django 3.2.4 on 2021-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='AllowGif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='GifPath',
            field=models.TextField(default=''),
        ),
    ]
