# Generated by Django 3.2.4 on 2021-10-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Path', models.CharField(max_length=100)),
                ('Extra', models.CharField(max_length=100)),
            ],
        ),
    ]
